### ISSUE TITLE
Header-only testing

### ISSUE THREAD

**Issue by ankane** [jasonroelofs/rice#149]
This tracks the testing status of #146 with existing projects.

[Header-only docs](https://github.com/cfis/rice/blob/dev/README.md)

Each project uses the `rice-header-only` branch

Project | Status | Diff | CI | Notes
--- | --- | --- | --- | ---
Midas | Success :tada: | [Diff](https://github.com/ankane/midas/compare/rice-header-only) | [CI](https://github.com/ankane/midas/actions) |
LIBFFM | Success :tada: | [Diff](https://github.com/ankane/libffm/compare/rice-header-only) | [CI](https://github.com/ankane/libffm/actions) |
IsoTree | Success :tada: | [Diff](https://github.com/ankane/isotree/compare/rice-header-only) | [CI](https://github.com/ankane/isotree/actions) |
YouTokenToMe | Success :tada: | [Diff](https://github.com/ankane/youtokentome/compare/rice-header-only) |  [CI](https://github.com/ankane/youtokentome/actions) |
OutlierTree | Success :tada: | [Diff](https://github.com/ankane/outliertree/compare/rice-header-only) | [CI](https://github.com/ankane/outliertree/actions) |
Faiss | Success :tada: | [Diff](https://github.com/ankane/faiss/compare/rice-header-only) | [CI](https://github.com/ankane/faiss/actions) |
FastText | Success :tada: | [Diff](https://github.com/ankane/fastText/compare/rice-header-only) | [CI](https://github.com/ankane/fastText/actions) |
DataSketches | Success :tada: | [Diff](https://github.com/ankane/datasketches/compare/rice-header-only) | [CI](https://github.com/ankane/datasketches/actions) |
OR-Tools | Success :tada: | [Diff](https://github.com/ankane/or-tools/compare/rice-header-only) | [CI](https://github.com/ankane/or-tools/actions) |
Torch.rb | Success :tada: | [Diff](https://github.com/ankane/torch.rb/compare/rice-header-only) | [CI](https://github.com/ankane/torch.rb/actions) |
TorchAudio | Success :tada: | [Diff](https://github.com/ankane/torchaudio/compare/rice-header-only) | [CI](https://github.com/ankane/torchaudio/actions) |
Tomoto | In-Progress | [Diff](https://github.com/ankane/tomoto/compare/rice-header-only) | [CI](https://github.com/ankane/tomoto/actions) | Mac error due to C++17, runtime segfault on Windows

Migration notes

- Use `rice/rice.hpp` instead of individual includes
- Use `define_function`/`define_singleton_function` instead of `define_method`/`define_singleton_method` when no `self` argument
- Use lambda instead of pointer to lambda
- Update conversion templates to use `Rice::detail` and use `Rice::detail::From_Ruby<T>::convert(object.value())` instead of `from_ruby<T>(object)` (similar with `to_ruby`)
- Remove outer parentheses from `Arg` list
- Automake is no longer needed

**Comment by cfis** [comment]
Ok, I think all the Rice issues for Faiss are now resolved. There are a couple failures in the tests, but they don't look Rice related to me.

**Comment by cfis** [comment]
Datasketches error was due to not having From_Ruby<unsigned char> which is now added (and I added signed char while at it).

**Comment by ankane** [comment]
Great, Faiss looking much better. Still seeing `bad any_cast` on Ubuntu 18.04, but not on Ubuntu 20.04 or Mac.

Just ran a new build for DataSketches, but still seeing errors on all platforms.

**Comment by ankane** [comment]
Hey @cfis, thanks for https://github.com/ankane/tomoto/issues/2. I converted `Object` to `VALUE` for `convert` in the other projects, and two more are now passing 🎉 

fastText and DataSketches are failing on similar code, but with different error messages.

fastText - `error: conversion from ‘tuple<fasttext::FastText&>’ to non-scalar type ‘tuple<fasttext::FastText>’ requested`

```cpp
    .define_method("dimension", &FastText::getDimension)
    .define_method("quantized?", &FastText::isQuant)
    .define_method("word_id", &FastText::getWordId)
    .define_method("subword_id", &FastText::getSubwordId)
```

DataSketches - `invalid abstract return type`

```cpp
    .define_method("empty?", &theta_sketch::is_empty)
```

I imagine they could be converted to lambdas if needed, but wanted to see if this way of defining methods was still supported.

For tomoto, I applied the patch, which improved things significantly, but now running into another compile time error on Mac and runtime errors on Linux and Windows. Will spend some more time on it to see if I can figure it out.

**Comment by cfis** [comment]
@ankane - Thanks for all the feedback.
On DataSketches, that was a bug. Fixed in b3c37d78886a5ac37a6e03c1c42443dee2e4dcec.

**Comment by cfis** [comment]
And fastText compiles for me now too. The tests run, but fail, all with the error "ArgumentError: test/support/unsupervised.txt cannot be opened for training!". I am assuming that is not Rice related, but if it is let me know.

**Comment by ankane** [comment]
Thanks @cfis, all tests now green for both of those. Working through the remaining projects now.

Is there a replacement for:

```cpp
Rice::Data_Object<MPObjective>(x, rb_cMPVariable, nullptr, nullptr);
```

[Rice 3 context](https://github.com/ankane/or-tools/blob/57013e4b6195632668c9d969f055da3d666d1117/ext/or-tools/linear.cpp#L42-L47)

**Comment by cfis** [comment]
Just remove the two nullptr's. Those were for mark and free functions, but I updated the library to use TypedData_Struct - as opposed to deprecated Data_Struct which supposedly is going to be finally removed in Ruby 3.1 according to compiler warning messages). Thus mark and free are now setup in Data_Type.

**Comment by ankane** [comment]
Hmm, will that disable the mark and free functions? Seeing `double free or corruption (out)` when switching to that.

Also, unrelated, it looks like `add_handler` now returns `Rice::Module` instead of `Rice::Class` for code like this:

```cpp
  Rice::define_class_under<torch::Device>(m, "Device")
    .add_handler<torch::Error>(handle_error)
    .define_constructor(Rice::Constructor<torch::Device, const std::string&>())
```

Error: `‘class Rice::Module’ has no member named ‘define_constructor’`

**Comment by cfis** [comment]
No - mark and free are handled differently now due to changes in Ruby itself (look in Data_Type if interested).

Double deletes - is the library passing you a reference or pointer? If so, you have to tell Rice to *not* free it. See this:

https://github.com/jasonroelofs/rice/blob/master/README.md#ownership

Previously Rice used to always assume ownership, and I left it that way. But over the last few days I've changed my mind and I think it should be the opposite - Rice does *not* take ownership except for object that itself creates via calling a C++ constructor. I'll open a separate ticket about that for discussion.

**Comment by cfis** [comment]
One other thing - if you don't implement To_Ruby correctly (meaning using perfect forwarding for references), you can take ownership when you don't mean too. I ran into that yesterday myself...thinking about what to do about it.

**Comment by ankane** [comment]
Re `add_handler`: using it to customize the exception message (`what_without_backtrace` instead of `what`), but there's probably a better way to do that.

```cpp
inline void handle_error(torch::Error const & ex)
{
  throw Rice::Exception(rb_eRuntimeError, ex.what_without_backtrace());
}
```

Re ownership: OR-Tools tests green with `Return().takeOwnership(false)`

**Comment by ankane** [comment]
Hey @cfis, think I narrowed down the issue with Torch.rb. Any idea why the first works but the second segfaults?

```cpp
inline VALUE wrap(torch::Tensor x) {
  return Rice::detail::To_Ruby<torch::Tensor>::convert(x);
}

static VALUE torch_ones(int argc, VALUE* argv, VALUE self_)
{
  auto dispatch_ones = []() -> torch::Tensor {
    return torch::ones({2, 3});
  };

  // works
  return Rice::detail::To_Ruby<torch::Tensor>::convert(dispatch_ones());

  // segfault
  return wrap(dispatch_ones());
}
```

For Tomoto, everything works great on Linux, but half of the classes segfault on Windows (haven't been able to find a pattern between the ones that work and ones that don't). Will continue to dig, but let me know if you have any ideas about what would cause this type of behavior.

**Comment by cfis** [comment]
Hmm...of the top of my head not sure on either question. I assume the first one has something to do with lvalues/rvalues and something not getting copied correctly but of the top of me head I don't see it. Would have to walk through it with a debugger to check.

**Comment by cfis** [comment]
@ankane - See what happens with the updates I just pushed with master. Note they will break your code.

To fix remove ```Return().takeOwnership(false)``` since that is now the default and thus won't compile. And then for the opposite issue, where Ruby *does* need to take ownership, do this:

````cpp
   define_function("method_that_returns_object_ruby_manages.", &.., Return().takeOwnership());
```
If you still run into issues let me know and I can take a look.

````cpp
   define_function("..", &.., Return().takeOwnership(false));
```

**Comment by ankane** [comment]
Great, have Torch.rb working locally, and will try the changes with OR-Tools. Can you regenerate `rice.hpp` when you have a chance?

Also, needed to wrap some `convert` calls with `Object`. Otherwise, ended up with integers. [Example](https://github.com/ankane/torch.rb/commit/7d87f7402d0372e2aa4d5cca81d8d8c7c3dd26d8#diff-e97d8b687435ed016e483ce250b240ec389403f9db1a118eb30d45e456a161a3R89)

```cpp
Array a;
a.push(Object(Rice::detail::To_Ruby<torch::Tensor>::convert(t, true)));
```

Is it possible to push `VALUE`s directly? Noticed the same for functions that return `VALUE`.

**Comment by cfis** [comment]
Yeah, VALUEs are pita. Since they are simply a typdef to long long, there is no way to specialize templates for them and they get incorrectly converted. Using Object solves that, but at the cost of a an extra allocation for each conversion. My thinking was most of the time you won't be passing VALUE to C++ functions so although annoying easy enough to deal with since it won't occur much (note that SELF is specifically handled since that is the most common occurrence). Are you passing VALUEs around a lot?

However, it would be good to have a solution. My best idea so far is a way tell Rice to not convert these values. Maybe something like this:

```cpp
VALUE workingWithValues(VALUE input)
{
  return input;
}

define_global_function("working_with_values", @workingWithValues, Arg("input").noConversion(), Return().noConversion());

-- or ---
define_global_function("working_with_values", @workingWithValues, Arg("input").isValue(), Return().isValue());
```

**Comment by ankane** [comment]
Ah, makes sense. Not using VALUEs a lot (mainly just in the example above), so not a big deal to wrap. The solution above looks clean (think I slightly prefer the 2nd one fwiw).

**Comment by ankane** [comment]
Also, seems like things are in a good spot with testing. Can run a final round of tests for all projects right before the header-only release.

**Comment by cfis** [comment]
Great. On tomoto - the segfaults on windows are with mingw64?

**Comment by ankane** [comment]
I believe so ([setup-ruby](https://github.com/ruby/setup-ruby) uses [RubyInstaller2](https://github.com/oneclick/rubyinstaller2) and the target is reported as `x64-mingw32` - logs from [latest run](https://github.com/ankane/tomoto/runs/2091280531?check_suite_focus=true)). It happens with about half the classes in the project that use inheritance.

**Comment by cfis** [comment]
Which branch are you using?

* rice-header-only-windows
* rice-header-only-windows-slda
* rice-header-only-windows-take2

**Comment by ankane** [comment]
rice-header-only is most recent.

**Comment by cfis** [comment]
I can reproduce the Mingw crash. It in Eigen's mersenne twister code.

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007fff9fe4fe95 in Eigen::Rand::MersenneTwister<long long __vector(4), 312, 156, 31, 13043109905998158313ull, 29, 6148914691236517205ull, 17, 8202884508482404352ull, 37, 18444473444759240704ull, 43, 6364136223846793005ull>::operator()() (this=0x19c9ee36190)
    at D:/src/tomoto/vendor/EigenRand/EigenRand/PacketRandomEngine.h:326
326                                     res = pxor(res, psrl64(res, _Lx));
(gdb) bt
#0  0x00007fff9fe4fe95 in Eigen::Rand::MersenneTwister<long long __vector(4), 312, 156, 31, 13043109905998158313ull, 29, 6148914691236517205ull, 17, 8202884508482404352ull, 37, 18444473444759240704ull, 43, 6364136223846793005ull>::operator()() (this=0x19c9ee36190)
    at D:/src/tomoto/vendor/EigenRand/EigenRand/PacketRandomEngine.h:326
```

My first thought is that this isn't a Rice bug, its a mingw64 issue with Eigen. If you look around https://gitlab.com/libeigen/eigen you'll see there seems to be issues with compiling with -O3, which is what is happening.  

Did this work with a previous version of Rice?

**Comment by ankane** [comment]
Hmm, interesting. Yeah, works with Rice 3 with both C++11 and C++17 (https://github.com/ankane/tomoto/compare/windows - build logs next to each commit), so thought it may be related to the header-only changes.

**Comment by cfis** [comment]
Hmm, yeah that would indicate its due to the changes.

**Comment by cfis** [comment]
If I change the make file to use -Og then the crash goes away...

**Comment by ankane** [comment]
It looks like there are reports of similar behavior with mingw + Eigen (as you mentioned earlier), so maybe the changes are causing that to surface. I think it's fine to move forward without this if you think it's unlikely to affect other Rice projects.

**Comment by cfis** [comment]
@ankane - When you get a chance, do you mind trying with the latest version of Rice. Two issues to be aware of:

* Currently stl support is now in rice/stl.hpp. So if you use std::string, you need to include that header.
* When defining methods, Rice will now verify that all the arguments and return types have been registered with Rice. If not, you'll get an exception at program startup. Hopefully the message will be obvious, and the fix is simple to do `define_class` calls in the right order.

**Comment by ankane** [comment]
Tested a few projects. Midas, Faiss, and DataSketches work well.

For fastText, seeing:

```txt
/usr/include/c++/9/bits/stl_pair.h:449:51: error: no match for ‘operator==’ (operand types are ‘const fasttext::Vector’ and ‘const fasttext::Vector’)
```

when wrapping a method that returns `std::vector<std::pair<std::string, Vector>>` (both with and without a custom `To_Ruby` method).

**Comment by ankane** [comment]
Also, not sure this round of changes was great for Rice user experience. Needed to:

1. Add classes in a specific order which wasn't previously required
2. Add extra enums and classes which weren't previously needed
3. Add an extra header since projects use `std::string`

**Comment by cfis** [comment]
On the operator ==, that is needed for implementing things like find and delete, etc. But the code checks for that. So will need to look into it.

On the other points:

1. How much of a pain is that? I figure its better to find out sooner that you missed something than later. Really I'd like code to not compile at all, but I'm not sure if that's doable or not in C+17 (well probably is, I haven't figured out how yet)

2. Not sure on this one, can you open tickets for those issues?

3. Yeah, I can open a ticket for that. I'm torn on whether its better to have 1 or 2 headers. For what its worth, pybind11 requires two. Not sure what they do with std::string. We could move std::string back to the main header.

**Comment by ankane** [comment]
Thanks.

For 1, the code isn't really missing anything (all the classes exist and it previously worked with header-only Rice), but now requires users to manage the order they're defined (something they didn't have to worry about before).

For 2, if you have a method like `define_function("some_method", [](SomeClass& val) { ... })`, you could previously use `From_Ruby` to convert a Ruby object to `SomeClass` without `define_class`/`define_enum`.

For 3, I think it's probably common enough to keep in the main header in either scenario.

**Comment by cfis** [comment]
For #2, actually you still can but you have to flag it as a built-in type:

```cpp
template <>
  struct is_builtin<std::string> : public std::true_type {};
```
What types are you running into that are like that?

Note that built-in is how Rice knows if its wrapping a C++ object or not. It would be nicer to be able to do this at compile time and check Data_Type<T> and therefore not have to have is_builtin at all. But I haven't figured out how to do that (I'm not sure it possible you need to set a value that is a contexpr which since it is const you can't do).

FYI - this may or may not have worked in previous versions of Rice. For example say you define d`From_Ruby<std::complex<int>>` but don't specialialize 'std::complex<int>&' or 'std::complex<int>*'. Then if you got either of those, you'd get a runtime exception.

**Comment by cfis** [comment]
On fastdText, it is a std::vector of std::pair<std::string, fasttext::Vector>.

std::pair defines operator()==. But it then much check fasttext::Vector::operator()==.

Rice looks for the top level operator==() but doesn't recurse down. Not sure how to do that yet...need to research it.

**Comment by ankane** [comment]
This file has a good example for 2: https://github.com/ankane/faiss/blob/rice-header-only/ext/faiss/index.cpp

A constructor takes a `faiss::MetricType` argument, but I'd like for users to be able to pass in a symbol, so there's a `From_Ruby<faiss::MetricType>` conversion to convert the symbol into a `faiss::MetricType`.

With the latest changes, `Rice::define_enum<faiss::MetricType>` is needed, even though creating a Ruby class for the enum isn't desired.

**Comment by cfis** [comment]
Ok, I have fastText compiling again (note I didn't try to run it). Updates are pushed.

And thanks for the example code from faiss, will take a look.

**Comment by ankane** [comment]
Hey @cfis, was looking at the `is_builtin` code but having trouble seeing how to use it for the Faiss case.

Also, it looks like there's now a similar issue type definition issue with fastText at runtime: `Type is not defined with Rice`.

**Comment by cfis** [comment]
The error message should tell you what type.

Look at stl/string.ipp or stl/complex.ipp for example usage of is_builtin.

**Comment by ankane** [comment]
Thanks, have `is_builtin` working now.

Is there a way to add the name of the function (or other context) where the type isn't defined? For fastText, it wants me to register `std::pair<fasttext::real, std::string>` but from what I can tell, it doesn't appear to be used.

There are functions that return `std::vector<std::pair<fasttext::real, std::string>>`, but there are templates for `is_builtin` and `To_Ruby` for that type.

**Comment by cfis** [comment]
Hmm...will have to take a look. ```is_builtin``` should avoid that - what you are really saying is you are going to copy data back and forth (fyi, if you have a better name than is_builtin let me know).

Bigger picture, we should just add support for std::pair. Probably just make it a 2 element array....and tuples a x element array.

**Comment by cfis** [comment]
@ankane - pushed built in support for std::pair, so you can remove the custom mappings you have for it if you'd like. I do run into a crash running the tests, but its a Ruby / Windows issue not a Rice issue.

**Comment by ankane** [comment]
Great, it's now working without without the extra `std::pair` mapping, but still not entirely sure why it was checking for that mapping when it shouldn't be used.

Also, it looks like the generated header needs updated on master. Would it be better to have a header that includes the others instead of a generated one?

**Comment by cfis** [comment]
There is a header like that - see rice/rice.hpp versus include/rice/rice.hpp (and same for stl.hpp). That is what is processed to generate the single file. It is also what I use for development to avoid constantly having to generate the single file.

The idea of a single file is make it easy to grab one file and put it in your project - you really don't need the gem at all. Of course that works a lot better once there is a stable release.

Its easy to hack if you want, update ruby/lib/mkmf-rice.rb to point to which header you want to use.

**Comment by ankane** [comment]
I think it'd probably be better for the gem to use the non-generated one, so when there are fixes on master, users can point their Gemfile to GitHub and everything works.

**Comment by cfis** [comment]
Hmm, maybe. But making that a global change would means the tests would use the master header file, and I think its better for them to use the combined file because its possible for the combined file to be broken while the master is not (which I've seen a couple times).

FYI, its easy to regenerate the files locally:

```ruby
rake headers
```

**Comment by jasonroelofs** [comment]
@ankane If you've got some time, could you do one more round of testing? There's been some change to how to implement and use `To_Ruby` and `From_Ruby` as per https://github.com/jasonroelofs/rice/issues/160.

**Comment by ankane** [comment]
Yeah, definitely. It looks like there are currently compilation errors with Ruby < 3 (`error: use of undeclared identifier 'rb_uint2num_inline'`). Also, Ruby 2.5 is now [EOL](https://www.ruby-lang.org/en/downloads/branches/), so you may consider dropping support for it in 4.0.

**Comment by jasonroelofs** [comment]
Good point re: Ruby 2.5, we can shut that one down.

**Comment by cfis** [comment]
Hmm, I've been using Ruby 2.7 without issue. Will track down when rb_uint2num_inline came to be. I'm using that instead of the macro so that we call it using detail::protect in case an exception is raised.

**Comment by cfis** [comment]
Its not Ruby 2.7/3.0 thing. Its a OS thing:

#if SIZEOF_INT < SIZEOF_LONG

Fix pushed.

**Comment by cfis** [comment]
@ankane - I removed is_builtin. So if you want to define your own To_Ruby/From_Ruby functions you need to specialize detail::Type. You can see examples in std::string, std::complex, Hash, etc.

I will update the docs shortly.

**Comment by ankane** [comment]
It looks like there are CI failures on Ubuntu and Mac, so will hold off on testing until those are resolved.

**Comment by cfis** [comment]
CI failures have been cleaned up - most of them were caused by MSVC++ counting index_sequences backwards versus GCC /Clang which process them forwards. I just changed the tests to avoid that compiler difference. The other failure is a bit random and caused by the Ruby garbage collector sometimes calling mark of an object it is going to free (usually it doesn't do that) - but its not a bug in Rice.

Anyway, definitely ready for testing and thanks for the help!

**Comment by ankane** [comment]
Great, things are mostly working. A few findings:

1. Seeing `type is not defined with Rice: Rice::Symbol` with OR-Tools. Fixed after adding:

```cp
namespace Rice::detail
{
  template<>
  struct Type<Rice::Symbol>
  {
    static bool verify()
    {
      return true;
    }
  };
}
```

2. Seeing `Type Rice::Hash is not registered` with Torch.rb for a method that returns a hash.

3. Seeing runtime errors for constructors with default arguments with Faiss and DataSketches (it looks like `nil` is being passed when arguments are omitted instead of the default).

**Comment by cfis** [comment]
Good catches. Pushed fixes for both issues.

I realized that I changed From_Ruby from a struct to a class (since you have to instantiate it and call a method on it), but I didn't change To_Ruby. I guess I can go either way on those (struct or class), but they should be the same.

**Comment by cfis** [comment]
@ankane  - For the default values, take a look at this (step 3 and then default arguments at the bottom):

https://github.com/jasonroelofs/rice/blob/master/doc/advanced/type_conversions.rst

If you add your own type conversions, its up to you to provide the default value now.

Here is how to update your code:

```cpp
  template<>
  class From_Ruby<faiss::MetricType>
  {
  public:
    From_Ruby() = default;

    From_Ruby(faiss::MetricType defaultValue) : defaultValue_(defaultValue)
    {
    }

    faiss::MetricType convert(VALUE x)
    {
      if (x == Qnil) {
        return defaultValue_;
      }

      auto s = Object(x).to_s().str();
      if (s == "inner_product") {
        return faiss::METRIC_INNER_PRODUCT;
      } else if (s == "l2") {
        return faiss::METRIC_L2;
      } else {
        // TODO throw argument error
        throw std::runtime_error("Invalid metric: " + s);
      }
    }

  private:
    faiss::MetricType defaultValue_;
  };
```

The logic behind the change is described in #160.

**Comment by ankane** [comment]
Hmm, the code gets rid of the error, but the default value isn't set correctly. Also, if I use the `std::optional` pattern from the docs, it doesn't detect the default value.

For DataSketches, I'm seeing the default argument issue with built-in types (`uint8_t` and `uint64_t`).

For Torch.rb, it's having trouble finding `rice.hpp` with Ruby 2.6. Relevant trace:

```txt
/home/runner/work/torch.rb/torch.rb/vendor/bundle/ruby/2.6.0/bundler/gems/rice-4ad34b5d691a/lib/mkmf-rice.rb:16: warning: already initialized constant MakeMakefile::CONFTEST_C
/opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/mkmf.rb:259: warning: previous definition of CONFTEST_C was here
checking for rice/rice.hpp in /home/runner/work/torch.rb/torch.rb/vendor/bundle/ruby/2.6.0/bundler/gems/rice-4ad34b5d691a/include... no
[more lines]
../../../../ext/torch/cuda.cpp:3:25: fatal error: rice/rice.hpp: No such file or directory
```

**Comment by cfis** [comment]
I realized after wrting the explanation above that Rice couldn't support the use case of using `define_enum` and setting a default enumerated value. And in fact, that was true for `define_class` and `define_vector` etc.

So sorry to change this again, but I also realized a better way to do this that would work for non-copyable C++ types which is passing the Arg instance to From_Ruby and To_Ruby. Docs and the code above updated.

As for uint8_t and int8_t (unsigned char and signed char), those did not support default types. So added that in. Not sure about uint64_t, that should be fine (unless its a pointer to a uint64_t - Rice doesn't support default values for pointers although actually it could do so now with this change).

As for not finding rice.hpp...not sure havent changed that bit in quite a while.

So I updated how this works and just pushed. The code above has been updated

**Comment by ankane** [comment]
Great, DataSketches is now working.

For Faiss, I'm seeing:

```txt
/home/runner/work/faiss/faiss/ext/faiss/index.cpp:38:41: error: no matching function for call to ‘Rice::Arg::defaultValue()’
   38 |         return this->arg_->defaultValue();
      |                                         ^
In file included from /home/runner/work/faiss/faiss/ext/faiss/utils.h:3,
                 from /home/runner/work/faiss/faiss/ext/faiss/index.cpp:13:
/home/runner/work/faiss/faiss/vendor/bundle/ruby/3.0.0/bundler/gems/rice-737dd6873246/include/rice/rice.hpp:1194:20: note: candidate: ‘template<class Arg_Type> Arg_Type& Rice::Arg::defaultValue()’
 1194 |   inline Arg_Type& Arg::defaultValue()
      |                    ^~~
/home/runner/work/faiss/faiss/vendor/bundle/ruby/3.0.0/bundler/gems/rice-737dd6873246/include/rice/rice.hpp:1194:20: note:   template argument deduction/substitution failed:
/home/runner/work/faiss/faiss/ext/faiss/index.cpp:38:41: note:   couldn’t deduce template parameter ‘Arg_Type’
   38 |         return this->arg_->defaultValue();
      |                                         ^
```

It seems a bit odd that each type needs to handle default arguments, since they'll all use the same pattern.

**Comment by cfis** [comment]
Yeah it a lot of annoying repeated boiler plate code. The reason is because  `From_Ruby` needs to be specialized for each type, and well, that is just how C++ class templates work. You could probably get rid of the extra constructor that takes an `Arg` using inheritance, but that isn't much of a win. Pybind has the same issue and uses a macro to avoid a lot of the boilerplate code, but I find macros hard to debug.

My thinking is users generally should not have to define custom `From_Ruby` and `To_Ruby`. If you read the pybind11 docs they say "In very rare cases" should you be making custom conversions.  I know you use it to avoid defining enums, but I'm hoping most people just use define_enum instead (fyi that Rice could probably auto define enum types - not the values - but the existence of them - which would solve your issue).

As for calling defaultValue, yes you need to include the type `defaultValue<faiss::MetricType>`.  Which is a good point, I updated the docs.

Last, the reason you aren't getting default values is because of this:

```cpp
(Rice::Arg("quantizer"), Rice::Arg("d"), Rice::Arg("nlist"), Rice::Arg("metric") = faiss::METRIC_L2));
```
The Rice::Args are enclosed in a parentheses and separated by the comma operator, which means that only the last Arg is passed to Rice so it puts it in position 1. To fix remove the parentheses :

```cpp
Rice::Arg("quantizer"), Rice::Arg("d"), Rice::Arg("nlist"), Rice::Arg("metric") = faiss::METRIC_L2);
```

This is the old style way of supporting 0 or more arguments - its been replaced by template parameter packs. I decided to remove the old support to simplify the code base (minus well get everything done at once), but I need to document that in the migration guide.

FYI - MSVC doesn't compile the Faiss bindings because it does not like the deferencing of lambdas, ie `*[]` doesn't work but `[]` works fine. See `set_index_parameter` and `nprobe=`

**Comment by ankane** [comment]
Great, removing the parentheses fixed it (have a feeling that may bite some users - not sure if there's a way to have it error in warn in that scenario).

Last outstanding issue is Torch.rb - still digging into it.

**Comment by ankane** [comment]
It looks like an issue with Ruby 2.6 and Ubuntu 16.04 (seeing the same issue finding `rice.hpp` with DataSketches and that combination).

**Comment by cfis** [comment]
I can see about raising an error with the comma operator. And yeah, an error on the missing header is a good idea.

Thanks for digging into Ubuntu 16.

**Comment by ankane** [comment]
Looks like that's the behavior when the compiler doesn't support C++17. Can probably just mention that in the error message if `find_header('rice/rice.hpp')` returns false.

**Comment by ankane** [comment]
Also, a few of the examples in the conversion docs need `public:`.

**Comment by cfis** [comment]
Ok, made those changes.

Anything else? Is Tomoto still not working?

**Comment by ankane** [comment]
Great, thanks. Yeah, still having issues with Tomoto on Windows, but not sure it should hold up the release.

**Comment by cfis** [comment]
Tomoto crashes on windows have nothing to do with Rice. They are caused by Ruby because in, for reason I don't understand, replaces c library functions with its own. In this case, flcose get mapped to rb_w32_fclose.

https://twitter.com/lefticus/status/1247885279639166979

**Comment by ankane** [comment]
Is the reason it works with Rice 3 that Rice builds a separate library?

**Comment by jasonroelofs** [comment]
That is a weird issue, and I was able to track down more details of lefticus' statement: https://github.com/NREL/OpenStudio/issues/3942

I would hazard a guess that Rice 3 works and hasn't shown this bug is because Rice 3 for Windows was mainly processed via mingw, which probably doesn't trigger the same linking fix-up as MSVC. But that's a pure guess at this point.

**Comment by cfis** [comment]
Yes, that's a good explanation by lefticus.

It is a Windows thing, not an msvc vs mingw thing. Note the tomoto CI runs are segfaulting on mingw, and I see the same thing with MSVC.  I haven't done an exhaustive search, but here is another link:

https://bugs.ruby-lang.org/issues/8569

Not sure why Rice 3 doesn't trigger it - I'd agree its likely due to building a separate library. Would have to debug the code to verify.

Anyway, I consider this a Ruby bug not a Rice bug.

**Comment by jasonroelofs** [comment]
I'm prepping the release of Rice 4, so it's probably time to close this issue out. @ankane thank you so much for all of your help testing these changes!
